/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as ConversionsRouteImport } from './routes/conversions'
import { Route as LinksRouteImport } from './routes/links'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as TraceIndexRouteImport } from './routes/trace.index'
import { Route as TraceAttributionIdRouteImport } from './routes/trace.$attributionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionsRoute = ConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceIndexRoute = TraceIndexRouteImport.update({
  id: '/trace/',
  path: '/trace/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceAttributionIdRoute = TraceAttributionIdRouteImport.update({
  id: '/trace/$attributionId',
  path: '/trace/$attributionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/conversions': typeof ConversionsRoute
  '/links': typeof LinksRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/trace/$attributionId': typeof TraceAttributionIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/trace/': typeof TraceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/conversions': typeof ConversionsRoute
  '/links': typeof LinksRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/trace/$attributionId': typeof TraceAttributionIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/trace': typeof TraceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuration': typeof ConfigurationRoute
  '/conversions': typeof ConversionsRoute
  '/links': typeof LinksRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/trace/$attributionId': typeof TraceAttributionIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/trace/': typeof TraceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuration'
    | '/conversions'
    | '/links'
    | '/campaigns/$campaignId'
    | '/trace/$attributionId'
    | '/campaigns/'
    | '/trace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuration'
    | '/conversions'
    | '/links'
    | '/campaigns/$campaignId'
    | '/trace/$attributionId'
    | '/campaigns'
    | '/trace'
  id:
    | '__root__'
    | '/'
    | '/configuration'
    | '/conversions'
    | '/links'
    | '/campaigns/$campaignId'
    | '/trace/$attributionId'
    | '/campaigns/'
    | '/trace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationRoute: typeof ConfigurationRoute
  ConversionsRoute: typeof ConversionsRoute
  LinksRoute: typeof LinksRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  TraceAttributionIdRoute: typeof TraceAttributionIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  TraceIndexRoute: typeof TraceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversions': {
      id: '/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof ConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/': {
      id: '/trace/'
      path: '/trace'
      fullPath: '/trace/'
      preLoaderRoute: typeof TraceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$attributionId': {
      id: '/trace/$attributionId'
      path: '/trace/$attributionId'
      fullPath: '/trace/$attributionId'
      preLoaderRoute: typeof TraceAttributionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationRoute: ConfigurationRoute,
  ConversionsRoute: ConversionsRoute,
  LinksRoute: LinksRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  TraceAttributionIdRoute: TraceAttributionIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  TraceIndexRoute: TraceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
